[package]
name = "underhanded-rs"
version = "0.1.0"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]

[dependencies]
iron = "0.5.1"
router = "0.5.1"

lazy_static = "0.1"

serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
